[package]
name = "threadpool_fractal"
version = "0.1.0"
authors = ["krotera <01101011@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.3"
image = "0.23"
